/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NametagCheckerIndexRouteImport } from './routes/nametag-checker/index'
import { Route as NametagCheckerScanExternalRouteImport } from './routes/nametag-checker/scan-external'
import { Route as NametagCheckerScanCameraRouteImport } from './routes/nametag-checker/scan-camera'
import { Route as NametagCheckerResultsRouteImport } from './routes/nametag-checker/results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NametagCheckerIndexRoute = NametagCheckerIndexRouteImport.update({
  id: '/nametag-checker/',
  path: '/nametag-checker/',
  getParentRoute: () => rootRouteImport,
} as any)
const NametagCheckerScanExternalRoute =
  NametagCheckerScanExternalRouteImport.update({
    id: '/nametag-checker/scan-external',
    path: '/nametag-checker/scan-external',
    getParentRoute: () => rootRouteImport,
  } as any)
const NametagCheckerScanCameraRoute =
  NametagCheckerScanCameraRouteImport.update({
    id: '/nametag-checker/scan-camera',
    path: '/nametag-checker/scan-camera',
    getParentRoute: () => rootRouteImport,
  } as any)
const NametagCheckerResultsRoute = NametagCheckerResultsRouteImport.update({
  id: '/nametag-checker/results',
  path: '/nametag-checker/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nametag-checker/results': typeof NametagCheckerResultsRoute
  '/nametag-checker/scan-camera': typeof NametagCheckerScanCameraRoute
  '/nametag-checker/scan-external': typeof NametagCheckerScanExternalRoute
  '/nametag-checker': typeof NametagCheckerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nametag-checker/results': typeof NametagCheckerResultsRoute
  '/nametag-checker/scan-camera': typeof NametagCheckerScanCameraRoute
  '/nametag-checker/scan-external': typeof NametagCheckerScanExternalRoute
  '/nametag-checker': typeof NametagCheckerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nametag-checker/results': typeof NametagCheckerResultsRoute
  '/nametag-checker/scan-camera': typeof NametagCheckerScanCameraRoute
  '/nametag-checker/scan-external': typeof NametagCheckerScanExternalRoute
  '/nametag-checker/': typeof NametagCheckerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nametag-checker/results'
    | '/nametag-checker/scan-camera'
    | '/nametag-checker/scan-external'
    | '/nametag-checker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/nametag-checker/results'
    | '/nametag-checker/scan-camera'
    | '/nametag-checker/scan-external'
    | '/nametag-checker'
  id:
    | '__root__'
    | '/'
    | '/nametag-checker/results'
    | '/nametag-checker/scan-camera'
    | '/nametag-checker/scan-external'
    | '/nametag-checker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NametagCheckerResultsRoute: typeof NametagCheckerResultsRoute
  NametagCheckerScanCameraRoute: typeof NametagCheckerScanCameraRoute
  NametagCheckerScanExternalRoute: typeof NametagCheckerScanExternalRoute
  NametagCheckerIndexRoute: typeof NametagCheckerIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nametag-checker/': {
      id: '/nametag-checker/'
      path: '/nametag-checker'
      fullPath: '/nametag-checker'
      preLoaderRoute: typeof NametagCheckerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nametag-checker/scan-external': {
      id: '/nametag-checker/scan-external'
      path: '/nametag-checker/scan-external'
      fullPath: '/nametag-checker/scan-external'
      preLoaderRoute: typeof NametagCheckerScanExternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nametag-checker/scan-camera': {
      id: '/nametag-checker/scan-camera'
      path: '/nametag-checker/scan-camera'
      fullPath: '/nametag-checker/scan-camera'
      preLoaderRoute: typeof NametagCheckerScanCameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nametag-checker/results': {
      id: '/nametag-checker/results'
      path: '/nametag-checker/results'
      fullPath: '/nametag-checker/results'
      preLoaderRoute: typeof NametagCheckerResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NametagCheckerResultsRoute: NametagCheckerResultsRoute,
  NametagCheckerScanCameraRoute: NametagCheckerScanCameraRoute,
  NametagCheckerScanExternalRoute: NametagCheckerScanExternalRoute,
  NametagCheckerIndexRoute: NametagCheckerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
